id: P1EEE0E27
initial_creation_type: input
source_metadata:
  title: 'MSV 1,05: Carmavastu'
  language: bo
  volumes:
    9357a9d7c53748db86c9d954125862ba:
      title: Carmavastūddāna
      base_file: Carmavastūddāna.txt
      work_id: W47234A83
    d6c1ec96a5924ead82256b980174e0ac:
      title: Koṭikarṇa, born with a golden ring in his ear, visits the Preta world
      base_file: Koṭikarṇa, born with a golden ring in his ear, visits the Preta world.txt
      work_id: WAEF6996E
    3a78975342a14b0fa9711ce33a3490e3:
      title: Rājagṛhanidāna
      base_file: Rājagṛhanidāna.txt
      work_id: W163EE11E
    ac98208349774ce6823dbbd62215aba6:
      title: Uddāna
      base_file: Uddāna.txt
      work_id: W2840B3B2
    dc121a9222af48d6b3bb7d093780329d:
      title: Vaiśālyānidāna
      base_file: Vaiśālyānidāna.txt
      work_id: W90926A28
    4d448f1c6ed2450bad46575deffcbb47:
      title: Various rules
      base_file: Various rules.txt
      work_id: W45A551B2
    ca48a8f9ae314595b1f2900ab4ea40b5:
      title: Why Koṭikarṇa visits Hell
      base_file: Why Koṭikarṇa visits Hell.txt
      work_id: W92A1F89A
    f24f8d62c9274dc79d108901081fd859:
      title: Why Koṭikarṇa was born with a golden ear-ring
      base_file: Why Koṭikarṇa was born with a golden ear-ring.txt
      work_id: W78785B6B
    70f0db01da3f4ea99b058349a35c2c82:
      title: Śrāvastyānidāna
      base_file: Śrāvastyānidāna.txt
      work_id: W4490E42B
  chapter_to_tile: {}
created_at: '2022-03-01T22:16:02.960171'
last_modified_at: '2022-03-01T22:16:02.960177'
